### ISSUE TITLE
How about translation?

### ISSUE THREAD

**Issue by olgierd-on-fire** [Aliin/forum#12]
It seems default language is English.

**Comment by Mortiferr** [comment]
That is correct for now. When we reach the v1.0 point we will consider translation but unfortunately right now I don't think that is a top priority. Once we are further along in the project we would love to translate it. Do you speak another language? What is it? Would you be interested in helping us translate once we are further along?

**Comment by olgierd-on-fire** [comment]
I can Korean. Of course.

**Comment by Mortiferr** [comment]
Thank you! I will mark you down for translation into Korean once we are ready. I'm creating a TODO list issue right now.
