### ISSUE TITLE
Love to help

### ISSUE THREAD

**Issue by Mortiferr** [Aliin/forum#5]
I'd love to help. I can focus on the design part if you'd like.

**Comment by Aliin** [comment]
Hi! Of course, happy to have you here! You can Focus on anything you like. Design would be great! It is not really my strength ;)

**Comment by Mortiferr** [comment]
Awesome! Btw, I saw this repo in the FCC Gitter chat :)

**Comment by Aliin** [comment]
Yeah haha I'm trying to get to the repo Gitter Chat but having some issues :( But anyway, great! Just feel free to Change or upload anything you want.

**Comment by Aliin** [comment]
Did it got into the Chat again haha added you. Okay! Oh I saw you have some repos? Gonna check them out :)

**Comment by Mortiferr** [comment]
I really have a lot of junk on my GitHub, haha, most of my projects are just sitting on my computer.
